spring.application.name=Habitacion-Test
# Puerto en 0 para que en los tests elija un puerto aleatorio y no choque con el 8180
server.port=0

# Base de datos en memoria H2 (Súper rápida para tests)
spring.datasource.url=jdbc:h2:mem:hp_habitacion_test;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# En test SIEMPRE queremos create-drop para empezar con la BD limpia cada vez
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Apagamos Eureka para que los tests no busquen el servidor
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false